accounts/urls.py
"""Defining URL patterns for accounts."""

from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns =[
    # include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path

from . import views

app_name = 'learning_logs'

urlpatterns=[
    # Home Page
    path('', views.index, name='index'),
    # Page that shows all topics.
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Page for adding a new topic.
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page for adding a new entry.
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),
    # Page for editing an entry.
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
]

ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts', include('accounts.urls')),
    path('', include('learning_logs.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    """A topic the user is learing about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    public = models.BooleanField(default=False)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text
    
class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a simple string representing the entry."""
        if len(self.text) > 50:
            return f'{self.text[:50]}...'
        else:
            return self.text

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text', 'public']
        labels = {'text': '',
                  'public': 'Make public'}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Resgister a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid:
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('learning_logs:index')
        
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic,Entry
from .forms import TopicForm, EntryForm

def index(request):
    """The home page for Learning Log."""
    return render(request, 'learning_logs/index.html')

def topics(request):
    """Show public topics."""
    public_topics = Topic.objects.filter(public=True)

    """Show private topics."""
    if request.user.is_authenticated:
        private_topics = Topic.objects.filter(
            public=False, owner=request.user).order_by('date_added')
    else: 
        private_topics = Topic.objects.none()
    context = {
        'public_topics': public_topics,
        'private_topics': private_topics,
    }
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    if topic.public is False:
        check_topic_owner(topic, request.user)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = TopicForm()
    else:
        # POST data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
        
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(topic, request.user)

    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
        
    # Display a blank or invalid form.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_topic_owner(topic, request.user)

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id = topic.id)
        
    context = {'entry': entry, 'topic':topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

def check_topic_owner(topic, user):
    if topic.owner != user:
        raise Http404

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Learning Log</title>

  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
<body>

  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
        Learning Log
      </a>

      <button
        class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle Navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'learning_logs:topics' %}">
              Topics</a></li>
        </ul> <!-- End of links on left side of navbar -->

        <!-- Account-related links -->
         <ul class="navbar-nav ms-auto mb-2 mb-md-0">

          {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text me-2">
                Hello, {{ user.username }}.</span></li>
                
            <li class="nav-item">
              <form action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token %}
                <button name="submit" class="btn btn-outline-secondary btn-sm">
                  Log out</button>
              </form></li>

          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">
              Register</a></li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">
              Log in</a></li>
          {% endif %}

         </ul> <!-- End of account-related links -->
      </div> <!-- Closes collapsible parts of navbar -->

    </div> <!-- Closes navbar's container -->
  </nav> <!-- End of navbar -->

<main class="container">
  <div class="pb-2 mb-2 border-bottom">
    {% block page_header %}{% endblock page_header %}
  </div>
  <div>
    {% block content %}{% endblock content %}
  </div>
</main>

</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
  <a class="text-decoration-none text-success" 
  href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
  <h4>Add a new entry:</h4>
{% endblock page_header %}

{% block content %}

  <form action="{% url 'learning_logs:edit_entry' topic.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type='submit' content='Edit entry' %}
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}

<div class="p-3 mb-4 bg-light border rounded-3">
  <div class="container-fluid py-4">
    <h1 class="display-3">Track your learning.</h1>

    <p class="lead">
      Make your own Learning Log, and keep a list of the topics you're
      learning about. Whenever you learn something new about a topic,
      make an entry summarizing what you've learned.
    </p>

    <a class="btn btn-primary btn-lg mt-1"
    href="{% url 'accounts:register' %}">Register &raquo;</a>
  </div>
</div>

{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
  <a class="text-decoration-none text-success" 
  href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
  <h4>Add a new entry:</h4>
{% endblock page_header %}

{% block content %}

  <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type='submit' content='Add entry' %}
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h2>Add a new topic:</h2>
{% endblock page_header %}


{% block content %}

  <form action="{% url 'learning_logs:new_topic' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type='submit' content='Add topic' %}
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
<h1>{{ topic.text }}</h1>
{% endblock page_header %}

{% block content %}

  <p>
    <a class="text-decoration-none text-success" 
    href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
  </p>


  {% for entry in entries %}
    <div class="card mb-3">
      <!-- Card header with timestamp and edit link -->
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small><a class="text-decoration-none text-success"  
        href="{% url 'learning_logs:edit_entry' entry.id %}">
        edit entry</a></small>
      </h4>
      <!-- Card body with entry text -->
       <div class="card-body">{{ entry.text|linebreaks }}</div>
    </div>
  {% empty %}
    <li>There are no entries for this topic yet.</li>
  {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
<h1>Topics</h1>
{% endblock page_header %}


{% block content %}
  <h2>Public Topics</h2>
  <ul class="list-group border-bottom pb-2 mb-4">
    {% for topic in public_topics %}
      <li class="list-group-item border-0">
        <a class="text-decoration-none text-success"
         href="{% url 'learning_logs:topic' topic.id %}">
          {{ topic.text }}</a> - by {{ topic.owner.username }}</li>
    {% empty %}
      <li class="list-group-item border-0">
        No public topics have been added yet.</li>
    {% endfor %}
  </ul>

  <h2>Your Private Topics</h2>
  <ul class="list-group border-bottom pb-2 mb-4">
    {% for topic in private_topics %}
      <li class="list-group-item border-0">
        <a class="text-decoration-none text-success"
         href="{% url 'learning_logs:topic' topic.id %}">
          {{ topic.text }}</a></li>
    {% empty %}
      <li class="list-group-item border-0">
        No privates topics have been added yet.</li>
    {% endfor %}
  </ul>

  <a class="text-decoration-none text-success" 
  href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>

{% endblock content %}